In [1]:
import pandas as pd

# Load the parquet file
df = pd.read_parquet('../series_train.parquet/id=0a418b57/part-0.parquet')

# Display the dataframe
df.head()

,step,X,Y,Z,enmo,anglez,non-wear_flag,light,battery_voltage,time_of_day,weekday,quarter,relative_date_PCIAT
0,0,-0.075242,-0.256743,-0.973791,0.038081,-72.952141,0.0,5.0,4202.000000,51250000000000,2,4,-9.0
1,1,-0.265893,-0.270508,-0.765470,0.077430,-52.849220,0.0,0.5,4185.333496,51255000000000,2,4,-9.0
2,2,0.334517,-0.548602,-0.588596,0.039162,-44.118084,0.0,11.5,4185.500000,51260000000000,2,4,-9.0
3,3,0.000193,-0.021069,-0.999681,0.001450,-88.759613,0.0,0.0,4185.666504,51265000000000,2,4,-9.0
4,4,-0.000685,-0.020681,-0.997677,0.000491,-88.756958,0.0,8.5,4185.833496,51270000000000,2,4,-9.0

In [2]:
missing_values = df.isnull().sum()
print(missing_values)

step                   0
X                      0
Y                      0
Z                      0
enmo                   0
anglez                 0
non-wear_flag          0
light                  0
battery_voltage        0
time_of_day            0
weekday                0
quarter                0
relative_date_PCIAT    0
dtype: int64

In [3]:
# Load the parquet file
test_df = pd.read_parquet('../series_test.parquet/id=001f3379/part-0.parquet')

# Display the dataframe
test_df.head()

,step,X,Y,Z,enmo,anglez,non-wear_flag,light,battery_voltage,time_of_day,weekday,quarter,relative_date_PCIAT
0,0,0.679618,-0.578170,0.320939,0.273671,18.857922,0.0,6.000000,4175.00,40260000000000,2,3,68.0
1,1,-0.139180,-0.727815,0.591056,0.083061,37.902840,0.0,1.500000,4174.75,40265000000000,2,3,68.0
2,2,-0.601730,-0.353205,0.675733,0.032478,44.337727,0.0,1.000000,4174.50,40270000000000,2,3,68.0
3,3,-0.379666,-0.283236,0.613746,0.074800,44.593758,0.0,55.200001,4174.25,40275000000000,2,3,68.0
4,4,0.397701,0.470948,-0.486966,0.070064,-31.758539,0.0,21.000000,4174.00,40280000000000,2,3,68.0

In [4]:
test_cross_sectional = pd.read_csv('../test.csv')

test_cross_sectional.head()

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,BIA-BIA_TBW,PAQ_A-Season,PAQ_A-PAQ_A_Total,PAQ_C-Season,PAQ_C-PAQ_C_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday
0,00008ff9,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,...,32.6909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,3.0
1,000fd460,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,...,27.0552,NaN,NaN,Fall,2.340,Fall,46.0,64.0,Summer,0.0
2,00105258,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,...,NaN,NaN,NaN,Summer,2.170,Fall,38.0,54.0,Summer,2.0
3,00115b9f,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,...,45.9966,NaN,NaN,Winter,2.451,Summer,31.0,45.0,Winter,0.0
4,0016bb22,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,...,NaN,Summer,1.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
train_cross_sectional = pd.read_csv('../train.csv')

train_cross_sectional.head()

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,00008ff9,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,...,4.0,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0
1,000fd460,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,...,0.0,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0
2,00105258,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,...,2.0,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0
3,00115b9f,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,...,3.0,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0
4,0016bb22,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import os

# Define the directory path
directory_path = '../series_train.parquet'

# Fetch the list of {id}s
ids = [name.split('=')[1] for name in os.listdir(directory_path) if os.path.isdir(os.path.join(directory_path, name)) and name.startswith('id=')]

print(ids[:5])

['00115b9f', '001f3379', '00f332d1', '01085eb3', '012cadd8']

In [7]:
filtered_train_cross_sectional = train_cross_sectional[train_cross_sectional['id'].isin(ids)]
filtered_train_cross_sectional.head()

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
3,00115b9f,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,...,3.0,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0
5,001f3379,Spring,13,1,Winter,50.0,Summer,22.279952,59.5,112.2,...,1.0,2.0,1.0,34.0,Summer,40.0,56.0,Spring,0.0,1.0
20,00f332d1,Winter,14,0,Spring,68.0,Spring,17.168636,66.5,108.0,...,2.0,2.0,2.0,47.0,Spring,30.0,43.0,Winter,2.0,1.0
22,01085eb3,Fall,12,0,Winter,58.0,Fall,34.187282,60.5,178.0,...,1.0,1.0,0.0,30.0,Fall,53.0,73.0,Fall,0.0,0.0
25,012cadd8,Spring,9,0,Winter,60.0,Fall,17.089151,53.2,68.8,...,0.0,0.0,0.0,9.0,Summer,27.0,40.0,Spring,0.0,0.0

In [13]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.utils.rnn as rnn_utils
import numpy as np

class TimeSeriesDataset(Dataset):
    def __init__(self, sequences, chunk_size=1000):
        self.sequences = sequences
        self.chunk_size = chunk_size
        
    def __len__(self):
        return len(self.sequences)
    
    def __getitem__(self, idx):
        sequence = self.sequences[idx]
        # Convert to tensor and ensure float32
        sequence = torch.FloatTensor(sequence)
        
        # If sequence is longer than chunk_size, average pool it
        if len(sequence) > self.chunk_size:
            # Reshape to (channels, length) for avg_pool1d
            sequence = sequence.transpose(0, 1).unsqueeze(0)
            target_length = self.chunk_size
            kernel_size = len(sequence[0, 0]) // target_length
            if kernel_size > 1:
                sequence = nn.functional.avg_pool1d(sequence, kernel_size)
            sequence = sequence.squeeze(0).transpose(0, 1)
        
        return sequence

def collate_fn(batch):
    # Sort sequences by length in descending order
    batch.sort(key=lambda x: len(x), reverse=True)
    
    # Get lengths of each sequence in the batch
    lengths = torch.LongTensor([len(x) for x in batch])
    
    # Pad sequences to the same length
    padded_seqs = rnn_utils.pad_sequence(batch, batch_first=True)
    
    return padded_seqs, lengths

class TimeSeriesTransformer(nn.Module):
    def __init__(self, input_dim=8, d_model=64, nhead=8, num_layers=3, dim_feedforward=256, max_sequence_length=1000):
        super().__init__()
        
        self.input_projection = nn.Linear(input_dim, d_model)
        
        # Add initial downsampling if needed
        self.downsample = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, d_model),
            nn.GELU()
        )
        
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=dim_feedforward,
            batch_first=True
        )
        
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )
        
        self.global_pool = nn.AdaptiveAvgPool1d(1)
        
    def forward(self, x, lengths):
        # x shape: (batch_size, max_seq_length, input_dim)
        x = self.input_projection(x)
        x = self.downsample(x)
        
        # Create padding mask for transformer
        max_len = x.size(1)
        device = x.device
        arange_tensor = torch.arange(max_len, device=device)[None, :]
        lengths_tensor = lengths[:, None].to(device)
        padding_mask = arange_tensor >= lengths_tensor
        
        x = self.transformer_encoder(x, src_key_padding_mask=padding_mask)
        
        # Global pooling across sequence length
        x = x.transpose(1, 2)  # (batch_size, d_model, max_seq_length)
        x = self.global_pool(x)  # (batch_size, d_model, 1)
        x = x.squeeze(-1)  # (batch_size, d_model)
        
        return x

class ContrastiveLoss(nn.Module):
    def __init__(self, temperature=0.5):
        super().__init__()
        self.temperature = temperature
        
    def forward(self, embeddings):
        # Normalize embeddings
        embeddings_normalized = nn.functional.normalize(embeddings, dim=1)
        
        # Compute similarity matrix
        similarity_matrix = torch.matmul(embeddings_normalized, embeddings_normalized.T)
        
        # Mask out self-similarity
        mask = torch.eye(similarity_matrix.size(0), device=similarity_matrix.device)
        mask = 1 - mask
        
        # Scale similarities by temperature
        similarity_matrix = similarity_matrix / self.temperature
        
        # Compute loss
        similarity_matrix = similarity_matrix * mask
        positives = similarity_matrix.exp().sum(dim=1)
        negatives = mask.sum(dim=1)
        
        loss = -torch.log(positives / negatives).mean()
        
        return loss

def train_transformer(all_participant_sequences, device='cuda' if torch.cuda.is_available() else 'cpu', chunk_size=1000):
    """
    Train the transformer model on all participant sequences
    """
    # Create dataset and dataloader with custom collate function
    dataset = TimeSeriesDataset(all_participant_sequences, chunk_size=chunk_size)
    dataloader = DataLoader(
        dataset, 
        batch_size=16,  # Reduced batch size
        shuffle=True,
        collate_fn=collate_fn
    )
    
    # Initialize model with smaller sequence length
    model = TimeSeriesTransformer(max_sequence_length=chunk_size).to(device)
    
    # Initialize optimizer with gradient clipping
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    
    # Use contrastive loss instead of reconstruction
    criterion = ContrastiveLoss(temperature=0.5).to(device)
    
    # Training loop
    num_epochs = 10
    for epoch in range(num_epochs):
        model.train()
        total_loss = 0
        
        for batch, lengths in dataloader:
            batch = batch.to(device)
            lengths = lengths.to(device)
            
            optimizer.zero_grad()
            
            # Get embeddings
            embeddings = model(batch, lengths)
            
            # Compute contrastive loss
            loss = criterion(embeddings)
            
            loss.backward()
            
            # Clip gradients
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            
            optimizer.step()
            
            total_loss += loss.item()
            
        print(f"Epoch {epoch+1}/{num_epochs}, Loss: {total_loss/len(dataloader):.6f}")
    
    return model

def prepare_sequence_data(df):
    """
    Prepare the sequence data by selecting relevant features and normalizing
    """
    # Select features for the sequence
    features = ['X', 'Y', 'Z', 'enmo', 'anglez', 'non-wear_flag', 'light', 'battery_voltage']
    sequence_data = df[features].values
    
    # Normalize the data
    mean = np.mean(sequence_data, axis=0)
    std = np.std(sequence_data, axis=0)
    normalized_data = (sequence_data - mean) / (std + 1e-8)
    
    return normalized_data

prepare_sequence_data(df)

array([[ 2.1349025 , -0.2609411 , -0.1592889 , ...,  0.        ,
        -0.4181028 ,  2.0992131 ],
       [ 1.9746901 , -0.27151594, -0.47034788, ...,  0.        ,
        -0.41560516,  2.0999465 ],
       [ 2.4244106 ,  0.1187826 , -0.19460283, ...,  0.        ,
        -0.4106098 ,  2.1006756 ],
       ...,
       [ 0.02781039, -0.68991184, -1.7645991 , ...,  0.        ,
        -0.42559582, -1.3435628 ],
       [-0.08098972,  0.07714732, -1.4048077 , ...,  0.        ,
        -0.42559582, -1.3435628 ],
       [-0.01776941, -0.5146862 , -1.7641716 , ...,  0.        ,
        -0.42559582, -1.3435628 ]], dtype=float32)

In [10]:
import os
from tqdm import tqdm

parquets = os.listdir('../series_train.parquet')
parquets = [f'../series_train.parquet/{parquet}/part-0.parquet' for parquet in parquets]

sequences = []

for i in tqdm(range(700)):
    parquet_file = parquets[i]
    df = pd.read_parquet(parquet_file)
    sequence = prepare_sequence_data(df)
    sequences.append(sequence)

print(sequences[0])

100%|██████████| 700/700 [00:34<00:00, 20.49it/s]

[[ 0.7448756   0.01234294 -1.4588959  ...  0.          0.05141887
   1.1958863 ]
 [ 0.7459088   0.01229113 -1.4544054  ...  0.          0.04501374
   1.1973675 ]
 [ 0.7464255   0.0119285  -1.4538274  ...  0.          0.03860861
   1.1988533 ]
 ...
 [ 1.5512804   1.5459477  -0.40007216 ...  0.         -0.20318492
  -2.0424688 ]
 [ 2.4651449   0.9659504   0.21675254 ...  0.         -0.20318492
  -2.0424688 ]
 [ 2.443523    0.30729747 -0.41867217 ...  0.         -0.20318492
  -2.0424688 ]]

In [11]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda

In [15]:
model = train_transformer(sequences, device, chunk_size=1000)

Epoch 1/10, Loss: -2.004648
Epoch 2/10, Loss: -2.008947
Epoch 3/10, Loss: -2.008952
Epoch 4/10, Loss: -2.008957
Epoch 5/10, Loss: -2.008963
Epoch 6/10, Loss: -2.008967
Epoch 7/10, Loss: -2.008972
Epoch 8/10, Loss: -2.008974
Epoch 9/10, Loss: -2.008977
Epoch 10/10, Loss: -2.008979

In [18]:
def get_embedding(model, sequence, device='cuda', chunk_size=1000):
    # Make sure model is in eval mode
    model.eval()
    
    # Create a single sequence dataset
    dataset = TimeSeriesDataset([sequence], chunk_size=chunk_size)
    # Get the first (and only) item
    processed_sequence = dataset[0]
    
    # Add batch dimension and move to device
    sequence_tensor = processed_sequence.unsqueeze(0).to(device)  # Shape: [1, seq_length, features]
    lengths = torch.LongTensor([len(processed_sequence)]).to(device)
    
    with torch.no_grad():  # Disable gradient computation
        embedding = model(sequence_tensor, lengths)
        
    return embedding.cpu().numpy()  # Return as numpy array

single_sequence = sequences[0]
embedding = get_embedding(model, single_sequence)

/opt/conda/lib/python3.11/site-packages/torch/nn/modules/transformer.py:380: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:178.)
  output = torch._nested_tensor_from_mask(output, src_key_padding_mask.logical_not(), mask_check=False)

In [19]:
print(embedding)

[[ 1.2072891  -1.285907    1.0724608  -0.9647128  -1.1721855   0.59914154
  -1.1655712  -1.1702367   1.3399656   0.8503978   0.36611465  1.1322119
  -1.1436546   0.60717887  0.41804457  0.4304364   1.7853976  -0.7040854
  -0.45579344  1.3113045  -0.16199487 -0.21923763 -1.5629803   1.6914625
   0.0046412  -1.1569494   0.810713   -0.50895745 -1.0304841   1.108252
  -0.22500947  0.6542294  -0.70435965  1.6573403  -0.26517263  1.130759
   1.4824502   0.57356733 -0.8271706  -1.5393142   0.59242177 -1.2127146
  -0.74388164  0.22022718 -2.1491644   0.18578534 -0.7996799   0.9271483
  -0.8307708  -0.06390779 -1.1665395   1.3903908  -1.030352    1.4521902
   1.0732347   0.6108448  -1.2699958  -0.68777955  0.7992131  -1.3558935
  -0.02727532 -1.1247472   1.018531    0.22591838]]

In [20]:
# Saving the model
torch.save({
    'model_state_dict': model.state_dict(),
    'chunk_size': model.chunk_size if hasattr(model, 'chunk_size') else 1000,
    'input_dim': model.input_projection.in_features,
    'd_model': model.input_projection.out_features,
}, 'transformer_checkpoint.pth')

In [21]:
# Loading the model
checkpoint = torch.load('transformer_checkpoint.pth')
model = TimeSeriesTransformer(
    input_dim=checkpoint['input_dim'],
    d_model=checkpoint['d_model']
).to(device)
model.load_state_dict(checkpoint['model_state_dict'])

single_sequence = sequences[0]
embedding = get_embedding(model, single_sequence)

print(embedding)

[[ 1.2072891  -1.285907    1.0724608  -0.9647128  -1.1721855   0.59914154
  -1.1655712  -1.1702367   1.3399656   0.8503978   0.36611465  1.1322119
  -1.1436546   0.60717887  0.41804457  0.4304364   1.7853976  -0.7040854
  -0.45579344  1.3113045  -0.16199487 -0.21923763 -1.5629803   1.6914625
   0.0046412  -1.1569494   0.810713   -0.50895745 -1.0304841   1.108252
  -0.22500947  0.6542294  -0.70435965  1.6573403  -0.26517263  1.130759
   1.4824502   0.57356733 -0.8271706  -1.5393142   0.59242177 -1.2127146
  -0.74388164  0.22022718 -2.1491644   0.18578534 -0.7996799   0.9271483
  -0.8307708  -0.06390779 -1.1665395   1.3903908  -1.030352    1.4521902
   1.0732347   0.6108448  -1.2699958  -0.68777955  0.7992131  -1.3558935
  -0.02727532 -1.1247472   1.018531    0.22591838]]